version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    container_name: shopit-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10
    restart: unless-stopped

  back:
    build:
      context: .
      dockerfile: back-end/Dockerfile
    container_name: shopit-back
    depends_on:
      postgres:
        condition: service_healthy # <= было service_started
    environment:
      # Activate the profile that project provides
      SPRING_PROFILES_ACTIVE: standalone

      # Override datasource to use Docker network hostnames
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}

      # Optional JVM tunables
      JAVA_OPTS: -XX:+UseContainerSupport -XX:MaxRAMPercentage=75
      SPRING_FLYWAY_ENABLED: "true"          # <= включаем Flyway
      SPRING_FLYWAY_SCHEMAS: "public,catalogue"
      SPRING_JPA_HIBERNATE_DDL_AUTO: "validate"
      # Server port (matches EXPOSE)
      SERVER_PORT: 8081
    ports:
      - "8081:8081"
    restart: unless-stopped

  manager:
    build:
      context: .
      dockerfile: manager/Dockerfile
    container_name: shopit-manager
    depends_on:
      - back
    environment:
      SPRING_PROFILES_ACTIVE: standalone
      # Point manager to the back-end service via Docker DNS
      SELMAG_SERVICE_CATALOGUE_URI: http://back:8081
      #SPRING_APPLICATION_JSON: '{"selmag":{"service":{"catalogue":{"uri":"http://back:8081"}}}}'
      JAVA_OPTS: -XX:+UseContainerSupport -XX:MaxRAMPercentage=75
      SERVER_PORT: 8080
    ports:
      - "8080:8080"
    restart: unless-stopped

volumes:
  db_data:
